import Head from "next/head";

import { Box, CardMedia } from "@mui/material";
import Navbar from "@/sections/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/sections/Hero/Hero";
import About from "@/sections/About/About";
import { relative } from "path";
import Explore from "@/sections/Explore/Explore";
import GetStarted from "@/sections/GetStarted/GetStarted";
import WhatsNew from "@/sections/Whatsnew";
import World from "@/sections/World";
import Insights from "@/sections/Insights";
import Feedback from "@/sections/Feedback";

export default function Home() {
  return (
    <>
      <Head>
        <title>WEB FRAMER MOTION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          background:
            "linear-gradient(rgb(15, 23, 42), rgb(88, 28, 135), rgb(15, 23, 42))",
          overflow: "hidden",
        }}
      >
        <Navbar />
        <Hero />

        <Box sx={{ position: "relative" }}>
          <About />
          <Box sx={{ zIndex: 0 }}>
            <Explore />
          </Box>
        </Box>
        <Box sx={{ position: "relative" }}>
          <GetStarted />
          <Box sx={{ zIndex: 0 }}></Box>
          <WhatsNew />
        </Box>
        <World />
        <Box sx={{ position: "relative" }}>
          <Insights />
          <Box sx={{ zIndex: 0 }}></Box>
          <Feedback />
        </Box>
        <Footer />
      </Box>
    </>
  );
}
